### ISSUE TITLE
Add to Order fails 

### ISSUE THREAD

**Issue by EDDYMENS** [mestafrica/mkoo#32]
Order is not being persisted since serving_at date and type is not synced

**Comment by faddai** [comment]
Please provide details on the issue so that I can look into it. I don't get what the issue is about, please explain further.

**Comment by EDDYMENS** [comment]
I keep getting serving_at can't be null and I think this is because the  `addOrderJob`   receives just the meal ids without the meal type and the serving_at time and its the only thing used during sync

**Comment by faddai** [comment]
Are you sure you have the latest changes from `develop`?

`App\Jobs\AddOrderJob` accepts `\Illuminate\Http\Request` and `App\Entities\Order` objects

https://github.com/mestafrica/mkoo/blob/develop/app/Jobs/AddOrderJob.php#L29

**Comment by EDDYMENS** [comment]
Ok so this was an issue with my migrations either I had this field from a migration I was experimenting with or one that existed sometime .. Will verify that later
